### ISSUE TITLE
Examples rest-api, healthcheck curl fails 

### ISSUE THREAD

**Issue by consultantEnrico** [TNO/knowledge-engine#573]
In the docker-compose.yml on line 5 the healtcheck failed. Removing the curl command and set it to true solved this.

**Comment by bnouwt** [comment]
Hi @consultantEnrico, thanks for reporting. It seems to be caused by the `curl` command not being available in Alpine linux.

Replacing the `curl -f http://localhost:8280/rest/sc` command with the `wget http://localhost:8280/rest/sc -O /dev/null` seems to solve the issue. The -O /dev/null is necessary to prevent a permission denied on writing the `wget` output to a file.

I will create a branch and fix this bug 👍
